# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Keep Thrifty
email: chris@keepthrifty.com
description: > # this means to ignore newlines until "baseurl:"
  Take control of your finances and schedule so you can pursue your dreams
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.keepthrifty.com" # the base hostname & protocol for your site

author:
  name: "Chris @ Keep Thrifty"
  twitter: keepthrifty
  picture: /assets/img/headshot-640.jpg

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author:
        name: Chris Durheim
        twitter: keepthrifty
        email: chris@keepthrifty.com
      image:
        height: 533
        width: 800
  - scope:
      path: ""
    values:
      content-upgrade: 5-steps-to-mini-retirement-cheat-sheet

social:
  name: Keep Thrifty
  links:
    - https://twitter.com/keepthrifty
    - https://www.facebook.com/christopherdurheim
    - https://www.linkedin.com/in/chrisdurheim/
    - https://plus.google.com/+ChrisDurheim
    - https://github.com/chrisdurheim
    - https://www.pinterest.com/keepthrifty/

lang: en-us

logo: /assets/img/simple-logo.png

permalink: /:title/

timezone: America/Chicago

# Build settings
markdown: kramdown

# Pagination settings
paginate: 5
paginate_path: "/pg:num/"

rss-imageW: 600
rss-imageH: 400

sass:
  sass_dir: assets/_sass
  style: compressed

tipue_search:
  include:
    pages: true

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jemoji
