# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Keep Thrifty
email: chris@keepthrifty.com
description: > # this means to ignore newlines until "baseurl:"
  Take control of your finances and schedule so you can live out your dreams and values
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.keepthrifty.com" # the base hostname & protocol for your site
twitter_username: keepthrifty
twitter:
  username: keepthrifty

permalink: /:title/

timezone: America/Chicago

# Build settings
markdown: kramdown

# Pagination settings
paginate: 5
paginate_path: "/pg:num/"

rss-imageW: 600
rss-imageH: 400

sass:
  sass_dir: _sass
  style: compressed

tipue_search:
  include:
    pages: true

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jemoji
