# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KeepThrifty
email: chris@keepthrifty.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts, tools, and lessons learned to help you reduce your spending,
  achieve financial freedom, and live better
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.keepthrifty.com" # the base hostname & protocol for your site
twitter_username: keepthrifty

permalink: /:year/:month/:day/:title/

timezone: America/Chicago

# Build settings
markdown: kramdown

# Pagination settings
paginate: 5
paginate_path: "/pg:num/"

collections:
  challenges:
    output: true
  recommendations:
    types: test

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji
