# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Keep Thrifty
email: chris@keepthrifty.com
description: > # this means to ignore newlines until "baseurl:"
  Personal finance blogger pursuing complete debt freedom through frugality, minimalism, and a whole bunch of awesome spreadsheets
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.keepthrifty.com" # the base hostname & protocol for your site
twitter_username: keepthrifty
twitter:
  username: keepthrifty

permalink: /:year/:month/:day/:title/

timezone: America/Chicago

# Build settings
markdown: kramdown

# Pagination settings
paginate: 7
paginate_path: "/pg:num/"


sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jemoji
